name: Deploy Application

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.15.1'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --production
      
    - name: Build application
      run: npm run build
      env:
        NODE_ENV: production
        NODE_OPTIONS: --max_old_space_size=4096
        
    - name: Fix remote permissions
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY_LIVE }}
        script: |
          sudo chown -R ${{ secrets.SERVER_USER }}:${{ secrets.SERVER_USER }} /home/ec2-user/labx-prc-repair/
          sudo chmod -R 755 /home/ec2-user/labx-prc-repair/
          
    - name: Deploy via Rsync
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY_LIVE }}
        REMOTE_HOST: ${{ secrets.SERVER_IP }}
        REMOTE_USER: ${{ secrets.SERVER_USER }}
        TARGET: /home/ec2-user/labx-prc-repair/
        ARGS: "-rlgoDzvc --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r --no-perms --no-owner --no-group --exclude=.next/cache"
        
    - name: Restart application
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY_LIVE }}
        script: |
          cd /home/ec2-user/labx-prc-repair/
          pm2 reload labx-prc-repair || pm2 start "npm run start" --name labx-prc-repair
          pm2 save
